dataloader fixex
TamakiSakura/OBJ2TEXT-Improved pull request #6
Opened 2018-03-28 18:54 UTC by UBCMark

2018-03-28 18:58 UTC, UBCMark commented on model_ptr.py
> +    def sample(self, features, encoder_input, encoder_output, states=None):
This is done by @Wendy-Xiao . I modified model.ptr based on her version

2018-03-28 20:45 UTC, TamakiSakura requested changes
Please resolve all issues below

2018-03-28 20:45 UTC, TamakiSakura commented on data_loader.py
> +            train_visual_features = h5py.File('/home/kwx/OBJ2TEXT-Improved/data/train2014_visual_features.hdf5', 'r')
use relative path

2018-03-28 20:45 UTC, TamakiSakura commented on data_loader.py
> +               dummy_object=0):
Explain the reason of changes in parameter orders - this affect all train*.py files.

2018-03-28 20:45 UTC, TamakiSakura commented on train_ptr.py
> +            layout_encoding, encoder_features = layout_encoder(label_seqs, location_seqs, visual_seqs, layout_lengths)
Not now

2018-03-28 20:45 UTC, TamakiSakura commented on train_gtf.py
> +    parser.add_argument('--vocab_path', type=str, default='/home/kwx/OBJ2TEXT-Improved/data/vocab.pkl',
Use relative path, absolute path is not allowed

2018-03-28 20:45 UTC, TamakiSakura commented on train_gtf.py
> +                             transform, args.batch_size, yolo,
I don't see any benefit of changing this

2018-03-28 21:27 UTC, UBCMark commented on data_loader.py
> +            train_visual_features = h5py.File('/home/kwx/OBJ2TEXT-Improved/data/train2014_visual_features.hdf5', 'r')
resolved

2018-03-28 21:31 UTC, UBCMark commented on train_gtf.py
> +                             transform, args.batch_size, yolo,
in each iteration, we check if `yolo == False` then we set `visual_seq == None`.

2018-03-28 21:35 UTC, UBCMark commented on data_loader.py
> +               dummy_object=0):
See why I added a yolo flag in train*.py

2018-03-29 04:24 UTC, TamakiSakura requested changes
Please check the below

2018-03-29 04:24 UTC, TamakiSakura commented on train_gtf.py
> +                        default='.data/annotations/captions_train2014.json',
？？？？

2018-03-29 04:24 UTC, TamakiSakura commented on train_gtf.py
> +                             transform, args.batch_size, yolo,
OK but we could still do yolo=yolo, why change the position of the parameter?

2018-03-29 06:16 UTC, merged